[package]
name = "dorothy"
version = "0.0.4"
edition = "2021"

[dependencies]
chrono = "0.4"
csv = "1.1"
native-windows-gui = "1.0"
native-windows-derive = "1.0"
rust-ini = "0.18"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
embed-resource = "1.7"
